#!/bin/bash

ip="10.5.32.1"
pat="/home/$USER/.bopirruu"

case $1 in 
  --help)
    echo "--help                Prints this help message"
    echo "--setup               Sets up bopirruu"
    echo "-S <package>          Sync package <package>"
    echo "-R <package>          Remove package <package>"
    echo "-U <package>          Update package <package>"
    ;;
  --setup)
    mkdir /home/$USER/.bopirruu
    sudo mv bopirruu /usr/bin/
    sudo chmod +x /usr/bin/bopirruu
    ;;
  -S)
    if [ "$2" != "" ]
    then
      mkdir $pat/$2 > /dev/null 2>&1
      mkdir $pat/$2/${2^} > /dev/null 2>&1
      curl -o $pat/$2/install.sh $ip/bor/$2/install.sh 2>&1
      curl -o $pat/$2/remove.sh $ip/bor/$2/remove.sh 2>&1
      corl -o $pat/$2/update.sh $ip/bor/$2/update.sh 2>&1
      curl -o $pat/$2/info.txt $ip/bor/$2/info.txt 2>&1
      sh $pat/$2/install.sh $ip
    else
      echo "Please input a package"
    fi
    ;;
  -R)
    if [ "$2" != ""]
    then
      sh $pat/$2/remove.sh
      rm -rf $pat/$2
    else
      echo "Please input a package"
    fi
    ;;
  -U)
    if [ "$2" != "" ]
    then
      sh $pat/$2/update.sh $ip
    else
      echo "Please input a package"
    fi
    ;;
    *)
      echo "Unknown Command. please run bopirruu --help for a list of commands"
    ;;
esac
